### ISSUE TITLE
I tried to install, I got this.. And after modification refresh it didn't worked for me...

### ISSUE THREAD

**Issue by hisatnam** [awebdesign/nexus#1]
Class Aweb\Nexus\Support\HigherOrderTapProxy located in C:/xampp/htdocs/ocl/system/library/aweb/nexus\Support\Traits\HigherOrderTapProxy.php does not comply with psr-4 autoloading standard. Skipping.

**Comment by awebdesign** [comment]
1. Make sure you installed composer r3quired packages or use the complete package from the release which already contains the vendor folder.
2. Change de php version to 7.3. For higher versions we did not done all the tests yes
